name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Ed"
          second-greeting: "Edd"
          third-greeting: "Eddy"

      - name: ha-ha
        uses: ./.github/actions/joke-action
